import type {
  NotePosition,
  NoteStyleMapItem,
  ThoughtNote,
} from "@/app/thoughts/types";

export const THOUGHTS_CANVAS_SIZE = {
  width: 8000,
  height: 5250,
  overscroll: 100,
} as const;

export const THOUGHT_NOTES: ThoughtNote[] = [
  {
    id: "q1",
    title: "耐心不是毅力带来的结果，而是具有长远目光的结果。",
    source: "认知觉醒",
    date: "2025.01.08",
    bgColor: "#EAF2ED",
    accentColor: "#528B71",
    thought:
      '以前总觉得耐心是一种硬撑，是明明着急还逼自己忍住。后来越来越觉得，真正的耐心不是和冲动对抗，而是看见很多事情本来就不会立刻给反馈。读书、写作、做产品、甚至理解自己，都有一个很长的沉默期；如果总想立刻看到结果，就会误把"还没长出来"当成"没有意义"。这句话提醒我，所谓长远目光，其实就是愿意相信那些暂时看不见的积累。',
    image: null,
  },
  {
    id: "q2",
    title: "习惯之所以难以改变，是因为它是自我巩固的——越用越强，越强越用。",
    source: "认知觉醒",
    date: "2025.02.15",
    bgColor: "#FFFBE0",
    accentColor: "#C9A227",
    thought:
      '其实偷懒是人的天性，理智脑对大脑的控制能力很弱，所以我们在生活中做的大部分决策往往源于本能和情绪，而非理智。大多数时候我们以为自己在思考，其实都是在对自身的行为和欲望进行合理化，俗称"找借口"。\n\n所以要想从既有的习惯中跳出来，最好的方法不是依靠自制力，而是依靠知识，因为依靠意志相当于是与本能脑和情绪脑作对抗，用理论逻辑实际案例说服或欺骗自己。',
    image: "/picture/image.png",
    imageCaption: "习惯的力量",
  },
  {
    id: "q3",
    title: "阅读量 < 思考量 < 行动量 < 改变量",
    source: "认知觉醒",
    bgColor: "#F1F3EE",
    accentColor: "#528B71",
    thought: "实践！实践！还是实践！因为很重要所以说三次！",
    image: "/picture/image3.png",
    imageCaption: "知行合一",
  },
  {
    id: "q4",
    title: "真正的行动力高手不是能同时做很多事的人，而是会想办法避免同时做很多事的人。",
    source: "认知觉醒",
    date: "2025.03.22",
    bgColor: "#FFFFFF",
    accentColor: "#528B71",
    thought:
      '"上山就上山，砍柴就砍柴，做饭就做饭，如果上山是为了砍柴，砍柴是为了做饭，那么心就会很累。"没有上山的每一步，就到不了砍柴的地方，没有认真的砍好每一根柴，就没有顺利做饭的基础。\n\n很多时候我们之所以会焦虑，就是因为总盯着最后的结果，总觉得只有"做到""完成""抵达"才算有价值，于是做这一步的时候想着下一步，做当下的时候惦记终点。所有看起来重要的结果，本质上都是由一个个当下堆出来的。\n\n所以我更想提醒自己的是，不是不需要目标，而是不要让目标压过当下。该上山的时候就认真上山，该砍柴的时候就专心砍柴，先别急着反复问"这件事最后能带来什么"，而是先把手上这一步做扎实。',
    image: null,
  },
  {
    id: "q5",
    title: "企业与用户交换的从来不是产品，而是价值。",
    source: "俞军产品方法论",
    bgColor: "#FFF9E6",
    accentColor: "#C9A227",
    thought:
      "企业以产品为媒介，与用户进行价值交换，达成创造商业价值的目的。而本质上，交换的不是产品这个媒介，而是产品背后的各种用户价值。\n\n用户购买或使用产品，是为了获取使用价值，但企业做产品却是为了获取交换价值。一言以蔽之，企业创造有交换价值的使用价值（用产品承载），然后用它跟用户交换钱、时间、承诺等企业需要的价值。",
    image: "/picture/image2.png",
    imageCaption: "价值交换",
  },
  {
    id: "q6",
    title: "想让一个人理解和接受一个道理，是要在他的偏好和认知结构内去实现的。",
    source: "俞军产品方法论",
    date: "2025.04.10",
    bgColor: "#FDFBF4",
    accentColor: "#C9A227",
    thought:
      "这句话对我最大的提醒是：很多沟通失败，并不是因为道理不对，而是因为我默认别人会按照我的路径去理解。可事实是，每个人的偏好、经验和认知结构都不一样，同一句话落到不同的人身上，含义可能完全不同。无论是做产品、写文案还是和人交流，真正有效的表达都不是把自己的逻辑讲完整，而是先找到对方能够进入的那扇门。",
    image: null,
  },
  {
    id: "q7",
    title: "词语的威力与它们所唤起的形象密切相关，跟本身的意思却毫无关系。",
    source: "乌合之众",
    bgColor: "#F0F4F8",
    accentColor: "#5B7A99",
    thought:
      "以前我会更关注一句话“准不准”，后来才慢慢意识到，很多时候人先接收的不是定义，而是画面、情绪和联想。一个词能不能打动人，往往不取决于它在字典里的解释，而取决于它在脑海里点亮了什么。这对我做表达和做产品都很有提醒：命名不是包装，而是认知入口。",
    image: null,
  },
  {
    id: "q8",
    title: "任何在用户体验上所做的努力，都是为了提高效率。",
    source: "用户体验要素",
    bgColor: "#FFFFFF",
    accentColor: "#D48C70",
    thought:
      '基本以两种主要形式体现出来："帮助人们工作得更快"和"减少他们犯错的概率"，所以转化率、触达率、ROI这些指标可以一定程度上衡量用户体验设计的好坏。',
    image: null,
  },
  {
    id: "q9",
    title: "他人的言行也许和我们的感受有关，但并不是我们感受的起因。",
    source: "非暴力沟通",
    date: "2025.03.28",
    bgColor: "#F8F6FA",
    accentColor: "#8B7AA8",
    thought:
      "这句话让我把情绪的主动权拿回来了一点。以前难受的时候很容易马上把原因归到别人身上，好像只要对方变了，我就会好起来。可往深一点看，真正被触碰的往往是自己心里某种没被照顾到的需要，比如被理解、被尊重、被回应。它不是替别人开脱，而是提醒我别把所有感受都交给别人保管。",
    image: null,
  },
  {
    id: "q10",
    title: "对他人的批评间接表达了我们尚未满足的需要。",
    source: "非暴力沟通",
    bgColor: "#F5F3F8",
    accentColor: "#8B7AA8",
    thought:
      "对他人的指责、批评、评论以及分析反映了我们的需要和价值观。如果我们通过批评来提出主张，人们的反应常常是申辩或反击。反之，如果直接说出我们的需要，其他人就较有可能作出积极的回应。",
    image: null,
  },
  {
    id: "q11",
    title: "不论你选择做什么，了解自己为什么要那样做。",
    source: "非暴力沟通",
    bgColor: "#FFFFFF",
    accentColor: "#8B7AA8",
    thought:
      '我越来越觉得，很多消耗不是事情本身太难，而是自己一边做、一边不知道为什么做。人在"不得不"里久了，会越来越麻木，也越来越委屈；但一旦把它重新翻译成"我为什么仍然选择这样做"，哪怕答案只是"我暂时还想承担这个结果"，心态都会不一样。这句话像是在提醒我，把选择权重新拿回来。',
    image: null,
  },
  {
    id: "q12",
    title: "自责是尚未满足的需要的可悲表达。",
    source: "非暴力沟通",
    date: "2025.05",
    bgColor: "#FCFCFA",
    accentColor: "#8B7AA8",
    thought:
      "来来回回读了两次这本书了，这次读完我清晰认识到我们缺少的也许不是沟通的方法，而是坦诚的心，这本书的目的从来不是鼓吹什么高级的对话技巧，事实上书中所提到的四要素表达技巧均是建立在坦诚沟通的基础上，他所避免的是人与人之间的词不达意，而非避免相互算计。",
    image: null,
  },
  {
    id: "q13",
    title: "大多数时候我们以为自己在思考，其实都是在对自身的行为和欲望进行合理化。",
    source: "认知觉醒",
    bgColor: "#EAF2ED",
    accentColor: "#528B71",
    thought:
      "很多时候我以为自己是在冷静分析，其实只是先被本能和情绪推着走，然后再补一套听起来合理的解释。它让我不再轻易相信脑中第一时间冒出来的理由，其实觉察比结论更重要，先看清自己是不是在先入为主，再谈判断。",
    image: null,
  },
  {
    id: "q14",
    title: "清晰力才是行动力。",
    source: "认知觉醒",
    bgColor: "#F1F3EE",
    accentColor: "#528B71",
    thought:
      '我很喜欢这句话的干脆，因为它直接把"行动力差"翻译成了"目标不够清楚"。很多拖延并不是因为懒，而是因为事情在脑子里还是一团雾，不知道先做什么、做到什么程度、下一步是什么。一旦把目标拆具体，很多本来需要意志力硬推的事情，反而会自然启动。',
    image: null,
  },
  {
    id: "q15",
    title: "复利曲线显示了价值积累的普遍规律：前期增长非常缓慢，但到达一个拐点后会飞速增长。",
    source: "认知觉醒",
    date: "2025.05.18",
    bgColor: "#FFFFFF",
    accentColor: "#528B71",
    thought:
      "这句话很像对抗焦虑的一剂解药。我们太容易用短期反馈来判断一件事值不值得做，于是看不到那些前期缓慢、后期爆发的积累。可真正重要的东西，往往都不是今天做、明天就显效，而是先熬过一段看起来没什么变化的日子。它提醒我，别用线性的期待去要求复利型的成长。",
    image: "/picture/image4.png",
    imageCaption: "复利曲线",
  },
  {
    id: "q16",
    title: "要想让自己高效成长，必须让自己始终处于舒适区的边缘。",
    source: "认知觉醒",
    bgColor: "#EAF2ED",
    accentColor: "#528B71",
    thought:
      "学会给“努力”划一条边界。不是越拼越好，也不是越安全越好，而是始终待在稍微费力、但还没把自己压垮的位置。太轻松不会长，太困难又容易退。很多时候真正有效的成长，不是猛冲，而是长期待在那个既不舒服、又还撑得住的边缘。",
    image: "/picture/image5.png",
    imageCaption: "舒适区边缘",
  },
  {
    id: "q17",
    title: "当我们没有足够清晰的指令或者目标时，就很容易选择享乐。",
    source: "认知觉醒",
    date: "2025.06.03",
    bgColor: "#FFFBE0",
    accentColor: "#C9A227",
    thought:
      '这句话把很多分心和拖延说得很透。不是我们天生只爱轻松，而是当目标模糊、指令不清时，大脑会本能地选择更省力的选项。享乐很多时候并不是主动追求，而是在"我也不知道现在该干嘛"的空白里自动发生的。所以和自己较劲之前，先把目标写清楚，往往更有用。',
    image: null,
  },
  {
    id: "q18",
    title: "用户不是自然人，而是需求的集合。",
    source: "俞军产品方法论",
    bgColor: "#FFF9E6",
    accentColor: "#C9A227",
    thought:
      "这句话非常能打破直觉。我们平时太习惯把“用户”想成某一类人，可真正驱动选择的，往往不是身份，而是当下浮现出来的那一个需求。一个人今天是低价拼多多用户，明天也可能为了速度而成为京东的用户。对我来说，这句话最大的提醒是：不要把人看死，要去看需求是怎么变的。",
    image: null,
  },
  {
    id: "q19",
    title: "有情境才有用户，脱离情境就没有用户。",
    source: "俞军产品方法论",
    bgColor: "#FDFBF4",
    accentColor: "#C9A227",
    thought:
      "我特别喜欢这句话的锋利，因为它直接把很多空泛的用户分析砍掉了。脱离场景谈用户偏好，常常只会得到一些看上去对、但实际上没法指导判断的结论。很多选择不是这个人“本来就这样”，而是他在那个时刻、那个约束条件下，只会这样选。理解场景，才是真正开始理解用户。",
    image: "/picture/image6.png",
    imageCaption: "用户场景",
  },
  {
    id: "q20",
    title: "用户感知到的价值，才是用户价值。",
    source: "俞军产品方法论",
    bgColor: "#FFF9E6",
    accentColor: "#C9A227",
    thought:
      "警惕自己别陷进“我以为”的陷阱。产品做得多好、功能多完整、逻辑多漂亮，那都是站在设计者视角看到的东西；真正决定价值的，是用户最后感知到了什么、记住了什么、愿不愿意为此付出成本。价值不是被设计出来就自动成立的，它要先被感受到，才算真的存在。",
    image: null,
  },
  {
    id: "q21",
    title: "边界是需要靠对和错双向界定的，所以试错和失败必然是产品开发过程的一部分。",
    source: "俞军产品方法论",
    date: "2025.07.22",
    bgColor: "#FFFFFF",
    accentColor: "#C9A227",
    thought:
      '我很喜欢这句话里的"对和错双向界定"。很多时候我们总希望每次尝试都成功，好像只有不失败才算稳妥。但如果从来没撞过边界，就意味着我们其实也不知道自己现在做到哪里、还能做到哪里。对产品、对能力、甚至对自己都是这样：失败不是偏离过程，它本身就是定义边界的一部分。',
    image: null,
  },
  {
    id: "q22",
    title: "影响大众想象力的不是事实本身，而是它所扩散和传播的方式。",
    source: "乌合之众",
    bgColor: "#F0F4F8",
    accentColor: "#5B7A99",
    thought:
      "这句话让我重新理解了“事实为什么有时说不动人”。很多时候问题不在于事实不够真，而在于它进入别人脑海的方式不够鲜明、不够集中、也不够可感。它对我最大的提醒不是去玩弄表达，而是要承认：信息只有被感知、被记住、被形成画面，才真正开始产生影响。",
    image: null,
  },
  {
    id: "q23",
    title: "群体从来不渴望真理。",
    source: "乌合之众",
    bgColor: "#F0F4F8",
    accentColor: "#5B7A99",
    thought:
      "这句话读起来很冷，但也很真实。它不是让我变得悲观，而是提醒我别天真地以为“把真理讲清楚”就足够了。很多时候人更愿意接受能安放情绪、确认立场、维持安全感的说法，而不是最准确的说法。看清这一点以后，我反而更能理解为什么表达方式、叙事结构和情绪氛围会这么重要。",
    image: null,
  },
  {
    id: "q24",
    title: '明确定义"成功的条件"，而不是定义"通向成功的路径"。',
    source: "用户体验要素",
    bgColor: "#FFF5ED",
    accentColor: "#D48C70",
    thought:
      '这句话很像一个做事提醒。很多人一开始就急着讨论怎么做、做几步、按什么流程推进，可如果连"什么叫成功"都没有说清楚，路径设计得越精细，可能跑偏得越远。对我来说，它提醒的是先校准终点，再优化路径；先把判断标准说清，再谈执行细节。',
    image: null,
  },
  {
    id: "q25",
    title: '产品形态不是由"功能"决定的，而是由"用户自身的感受和行为"决定的。',
    source: "用户体验要素",
    date: "2025.08.14",
    bgColor: "#FFFFFF",
    accentColor: "#D48C70",
    thought:
      '我特别认同这句，因为它逼着人把注意力从"我要摆什么功能"转到"用户会怎么感受、怎么行动"上。很多设计之所以别扭，不是功能缺了，而是它工作的方式不符合人的直觉。产品不是把功能拼上去就结束了，更重要的是它在用户心里是否像一个自然成立的东西。',
    image: null,
  },
  {
    id: "q26",
    title: "文档不能解决问题，但定义可以。",
    source: "用户体验要素",
    bgColor: "#FFF5ED",
    accentColor: "#D48C70",
    thought:
      "这句话让我意识到，很多时候大家并不是缺少文档，而是缺少对问题边界的共识。文档可以记录、传递、追溯，但如果最关键的定义本身是模糊的，写得再详细也只是在放大混乱。真正省时间的，从来不是多写几页，而是先把那个核心定义讲明白。",
    image: null,
  },
  {
    id: "q27",
    title: "用户说出来的未必是他们真正想要的。",
    source: "用户体验要素",
    bgColor: "#FFFFFF",
    accentColor: "#D48C70",
    thought:
      "这句话很适合拿来提醒自己别把用户反馈当成答案本身。人会用自己最容易说出口的方式描述问题，但说出来的诉求背后，往往还藏着更真实的动机和限制。做产品也好，和人沟通也好，如果只停在表层表达，很容易做对动作却没碰到问题。",
    image: null,
  },
  {
    id: "q28",
    title: "感受根源于我们自身的需要。",
    source: "非暴力沟通",
    bgColor: "#F8F6FA",
    accentColor: "#8B7AA8",
    thought:
      "我觉得这句话很有力量，因为它把感受从外界手里拿了回来。以前会觉得是某个人、某件事“让我”难过、生气、失落，可如果继续往下问，就会发现真正发痛的地方其实是自己的需要。它让我学着不只是盯着触发事件，而是回过头去看：我到底在乎什么、缺了什么。",
    image: null,
  },
  {
    id: "q29",
    title: "观察和评论不是一回事。",
    source: "非暴力沟通",
    bgColor: "#F5F3F8",
    accentColor: "#8B7AA8",
    thought:
      "这句话看似简单，其实很难做到。我们太容易把自己的判断包装成事实，以为自己只是在描述，实际上已经把立场塞进去了。一旦观察和评论混在一起，对方听到的往往就不是信息，而是审判。所以这句话对我来说更像一个提醒：先把事实站稳，再让理解慢慢长出来。",
    image: null,
  },
  {
    id: "q30",
    title: '从"不得不"转换为"选择做"。',
    source: "非暴力沟通",
    bgColor: "#FFFFFF",
    accentColor: "#8B7AA8",
    thought:
      '我很喜欢这句的转换感。很多压抑和抵触，都是因为我们一直在用"不得不"跟自己说话，好像生活里所有事都只是被迫接受。可一旦把它改成"我现在选择这样做"，哪怕选择背后仍然有现实压力，人的姿态也会从被拖着走，变成主动承担后果。这种差别，会让人更清醒，也更自由。',
    image: null,
  },
  {
    id: "q31",
    title: "成长权重对比",
    source: "认知觉醒",
    bgColor: "#FFFFFF",
    accentColor: "#5B7A99",
    thought: "",
    image: "/picture/image7.png",
    imageCaption: "成长权重对比",
    imageWidth: 2429,
    imageHeight: 909,
    imageOnly: true,
  },
  {
    id: "q32",
    title: "用户体验的五个层次",
    source: "用户体验要素",
    bgColor: "#FFFFFF",
    accentColor: "#D48C70",
    thought: "",
    image: "/picture/image8.png",
    imageCaption: "体验层次图",
    imageWidth: 2129,
    imageHeight: 2865,
    imageOnly: true,
  },
  {
    id: "q33",
    title: "会飞的自己坐标系",
    source: "认知觉醒",
    bgColor: "#FFFFFF",
    accentColor: "#5B7A99",
    thought: "",
    image: "/picture/image9.png",
    imageCaption: "会飞的自己",
    imageWidth: 1357,
    imageHeight: 861,
    imageOnly: true,
  },
];

export const NOTE_POSITIONS: NotePosition[] = [
  { id: "q1", x: 2743, y: 1669, r: -1 },
  { id: "q2", x: 2780, y: 2730, r: 1 },
  { id: "q3", x: 3774, y: 2503, r: -2 },
  { id: "q4", x: 3761, y: 3514, r: 1 },
  { id: "q5", x: 4645, y: 2219, r: 7.7 },
  { id: "q6", x: 1854, y: 1919, r: 3.6 },
  { id: "q7", x: 3763, y: 1494, r: -1 },
  { id: "q8", x: 5606, y: 2034, r: 2 },
  { id: "q9", x: 881, y: 2098, r: -1 },
  { id: "q10", x: 2839, y: 1206, r: 1 },
  { id: "q11", x: 1871, y: 3218, r: -2 },
  { id: "q12", x: 2863, y: 4046, r: 1 },
  { id: "q13", x: 4826, y: 3921, r: -1 },
  { id: "q14", x: 1963, y: 1538, r: 2 },
  { id: "q15", x: 4734, y: 1411, r: -1 },
  { id: "q16", x: 2935, y: 2276, r: 1 },
  { id: "q17", x: 1779, y: 3736, r: -1 },
  { id: "q18", x: 4755, y: 3338, r: 2 },
  { id: "q19", x: 4595, y: 2778, r: -1 },
  { id: "q20", x: 3755, y: 4255, r: 1 },
  { id: "q21", x: 6645, y: 1559, r: -1 },
  { id: "q22", x: 3681, y: 969, r: 2 },
  { id: "q23", x: 3805, y: 2049, r: -2 },
  { id: "q24", x: 5634, y: 3626, r: 1 },
  { id: "q25", x: 5599, y: 1170, r: -2.9 },
  { id: "q26", x: 5666, y: 2611, r: 2 },
  { id: "q27", x: 5605, y: 3051, r: -1 },
  { id: "q28", x: 2908, y: 3453, r: 1 },
  { id: "q29", x: 1939, y: 2678, r: -8.8 },
  { id: "q30", x: 3754, y: 3026, r: 2 },
  { id: "q31", x: 900, y: 980, r: -3.5 },
  { id: "q32", x: 6460, y: 2190, r: 4.2 },
  { id: "q33", x: 6420, y: 3730, r: -2.4 },
];

export const NOTE_STYLE_MAP: Record<string, NoteStyleMapItem> = {
  q1: {
    variant: "diary-border",
    width: 520,
    backgroundColor: "#FCFBF7",
    accentColor: "#596C68",
    displayFont: "xiaowei",
  },
  q2: {
    variant: "diary-date",
    width: 480,
    backgroundColor: "#FCFCFA",
    accentColor: "#78858B",
    day: "15",
    monthYear: "FEBRUARY 2025",
  },
  q3: {
    variant: "tape-center",
    width: 380,
    backgroundColor: "#F1F3EE",
    accentColor: "#528B71",
    hint: "click to read",
    displayFont: "longcang",
    titleNoWrap: true,
  },
  q4: {
    variant: "diary-tape",
    width: 500,
    backgroundColor: "#FCFBF7",
    accentColor: "#596C68",
  },
  q5: {
    variant: "pin-round",
    width: 400,
    backgroundColor: "#FFF9E6",
    accentColor: "#C9A227",
    decoratorColor: "#C0B090",
    hint: "tap →",
    displayFont: "handwriting",
  },
  q6: {
    variant: "diary-border",
    width: 480,
    backgroundColor: "#FCFBF7",
    accentColor: "#C9A227",
  },
  q7: {
    variant: "minimal",
    width: 420,
    backgroundColor: "#F0F4F8",
    accentColor: "#5B7A99",
    borderColor: "#D8E2EC",
    eyebrow: "#乌合之众",
    displayFont: "xiaowei",
  },
  q8: {
    variant: "badge",
    width: 400,
    backgroundColor: "#FFFFFF",
    accentColor: "#D48C70",
    eyebrow: "✦ UX",
  },
  q9: {
    variant: "diary-date",
    width: 480,
    backgroundColor: "#FCFCFA",
    accentColor: "#8B7AA8",
    day: "28",
    monthYear: "MARCH 2025",
  },
  q10: {
    variant: "tape-purple",
    width: 400,
    backgroundColor: "#F8F6FA",
    accentColor: "#8B7AA8",
    hint: "非暴力沟通",
    displayFont: "longcang",
  },
  q11: {
    variant: "minimal",
    width: 380,
    backgroundColor: "#FFFFFF",
    accentColor: "#8B7AA8",
    hint: "Mindfulness",
    displayFont: "xiaowei",
  },
  q12: {
    variant: "tape-side-date",
    width: 420,
    backgroundColor: "#FCFCFA",
    accentColor: "#8B7AA8",
    sideLabel: "2025.05",
    hint: "tap to read",
    displayFont: "handwriting",
  },
  q13: {
    variant: "snippet",
    width: 420,
    backgroundColor: "#F6F5ED",
    accentColor: "#596C68",
    eyebrow: "◇ snippet",
    displayFont: "longcang",
  },
  q14: {
    variant: "pin-center",
    width: 300,
    backgroundColor: "#F0EFE6",
    decoratorColor: "#A84A3B",
    displayFont: "zhimang",
    titleNoWrap: true,
  },
  q15: {
    variant: "diary-border",
    width: 480,
    backgroundColor: "#FCFBF7",
    accentColor: "#596C68",
  },
  q16: {
    variant: "tape-irregular",
    width: 400,
    backgroundColor: "#FFFCE8",
    accentColor: "#528B71",
    displayFont: "handwriting",
  },
  q17: {
    variant: "diary-tape",
    width: 480,
    backgroundColor: "#FCFBF7",
    accentColor: "#596C68",
  },
  q18: {
    variant: "clip",
    width: 380,
    backgroundColor: "#F0F5F2",
    accentColor: "#78858B",
    decoratorColor: "#78858B",
    displayFont: "longcang",
  },
  q19: {
    variant: "tape-yellow",
    width: 420,
    backgroundColor: "#FDFBF4",
    accentColor: "#C9A227",
    hint: "Context matters",
    displayFont: "xiaowei",
  },
  q20: {
    variant: "warm-bar",
    width: 400,
    backgroundColor: "#FAF5ED",
    accentColor: "#E1C699",
    hint: "Value",
    displayFont: "handwriting",
  },
  q21: {
    variant: "diary-date",
    width: 480,
    backgroundColor: "#FCFCFA",
    accentColor: "#C9A227",
    day: "22",
    monthYear: "JULY 2025",
  },
  q22: {
    variant: "tape-yellow",
    width: 420,
    backgroundColor: "#EAF2ED",
    accentColor: "#528B71",
    eyebrow: "#乌合之众",
    displayFont: "longcang",
  },
  q23: {
    variant: "pin-center",
    width: 300,
    backgroundColor: "#F0EFE6",
    decoratorColor: "#5B7A99",
    displayFont: "zhimang",
    titleNoWrap: true,
  },
  q24: {
    variant: "badge",
    width: 420,
    backgroundColor: "#FFFDF2",
    accentColor: "#D48C70",
    eyebrow: "✦ UX",
    displayFont: "xiaowei",
  },
  q25: {
    variant: "diary-border",
    width: 480,
    backgroundColor: "#FCFBF7",
    accentColor: "#D48C70",
  },
  q26: {
    variant: "tape-irregular",
    width: 360,
    backgroundColor: "#FFFCE8",
    accentColor: "#D48C70",
    displayFont: "longcang",
    titleNoWrap: true,
  },
  q27: {
    variant: "badge",
    width: 400,
    backgroundColor: "#FFFFFF",
    accentColor: "#78858B",
    borderColor: "#78858B",
    eyebrow: "— UX",
    displayFont: "xiaowei",
  },
  q28: {
    variant: "clip",
    width: 380,
    backgroundColor: "#F5F3F8",
    accentColor: "#8B7AA8",
    decoratorColor: "#8B7AA8",
    displayFont: "handwriting",
  },
  q29: {
    variant: "pin-center",
    width: 320,
    backgroundColor: "#F0EFE6",
    decoratorColor: "#8B7AA8",
    displayFont: "zhimang",
    titleNoWrap: true,
  },
  q30: {
    variant: "minimal",
    width: 340,
    backgroundColor: "#FFFFFF",
    accentColor: "#8B7AA8",
    hint: "tap to read",
    titleNoWrap: true,
  },
  q31: {
    variant: "polaroid",
    width: 420,
    backgroundColor: "#FFFFFF",
    accentColor: "#5B7A99",
  },
  q32: {
    variant: "tape-portrait-photo",
    width: 340,
    backgroundColor: "#FFFFFF",
    accentColor: "#D48C70",
  },
  q33: {
    variant: "corner-photo",
    width: 420,
    backgroundColor: "#FFFFFF",
    accentColor: "#5B7A99",
  },
};
